version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-users
    overwrite: true
hooks:
  BeforeInstall:
    - location: preinstall.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: install.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: root
